import { Gender, GradeLevel } from '@/modules/users/consts';
import type { StudentListPaginator } from '@/modules/users/types';
import { UserRole } from '@/lib/types';

export const mockStudentData: StudentListPaginator = {
    data: [
        {
            id: '1',
            user: {
                id: '101',
                is_active: true,
                role: UserRole.Student,
            },
            full_name: 'Nguyễn Văn Duy',
            dob: '2015-05-20',
            gender: Gender.Male,
            grade_level: GradeLevel.Grade3,
            parent_name: 'Nguyễn Văn Hùng',
            parent_phone: '0987654321',
            address: '123 Đường Cầu Giấy, Hà Nội',
            note: 'Học sinh giỏi toán, cần chú ý kèm cặp thêm tiếng Anh.',
        },
        {
            id: '2',
            user: {
                id: '102',
                is_active: true,
                role: UserRole.Student,
            },
            full_name: 'Lê Thị Mai Anh',
            dob: '2010-11-12',
            gender: Gender.Female,
            grade_level: GradeLevel.Grade8,
            parent_name: 'Trần Thị Lan',
            parent_phone: '0912345678',
            address: 'Số 45 Ngõ 102, Quận Đống Đa, Hà Nội',
            note: null,
        },
        {
            id: '3',
            user: {
                id: '103',
                is_active: true,
                role: UserRole.Student,
            },
            full_name: 'Phạm Minh Hoàng',
            dob: '2018-02-28',
            gender: Gender.Male,
            grade_level: GradeLevel.Grade0,
            parent_name: 'Phạm Minh Đức',
            parent_phone: '0333444555',
            address: 'Chung cư HH Linh Đàm, Hoàng Mai, Hà Nội',
            note: 'Trẻ năng động, thích vẽ.',
        },
        {
            id: '4',
            user: {
                id: '104',
                is_active: true,
                role: UserRole.Student,
            },
            full_name: 'Hoàng Ngọc Linh',
            dob: '2008-09-05',
            gender: Gender.Female,
            grade_level: GradeLevel.Grade10,
            parent_name: 'Hoàng Tuấn',
            parent_phone: '0977888999',
            address: 'Khu đô thị Ciputra, Tây Hồ, Hà Nội',
            note: 'Học sinh mới chuyển trường từ TP.HCM.',
        },
        {
            id: '5',
            user: {
                id: '105',
                is_active: false,
                role: UserRole.Student,
            },
            full_name: 'Trần Bảo Nam',
            dob: '2013-07-15',
            gender: Gender.Other,
            grade_level: GradeLevel.Grade5,
            parent_name: 'Lê Mỹ Dung',
            parent_phone: '0909000111',
            address: 'Số 10 Tràng Thi, Hoàn Kiếm, Hà Nội',
            note: 'Gia đình yêu cầu bảo mật thông tin liên lạc.',
        },
    ],
    links: {
        first: 'http://localhost:8000/api/students?page=1',
        last: 'http://localhost:8000/api/students?page=1',
        next: null,
        prev: null,
    },
    meta: {
        current_page: 1,
        from: 1,
        last_page: 1,
        per_page: 10,
        to: 5,
        total: 5,
        links: [
            {
                url: null,
                label: '&laquo; Previous',
                active: false,
                page: null,
            },
            {
                url: 'http://localhost:8000/api/students?page=1',
                label: '1',
                active: true,
                page: null,
            },
            {
                url: null,
                label: 'Next &raquo;',
                active: false,
                page: null,
            },
        ],
    },
};
